version: 2
jobs:
  build:
    docker:
      - image: codegram/decidim
        environment:
          SIMPLECOV: true
          DATABASE_USERNAME: postgres
      - image: postgres
        environment:
          POSTGRES_USER: postgres
    parallelism: 1
    working_directory: /code
    steps:
      - run:
          name: Install PhantomJS
          command: |
            curl -OLk https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
            tar xvjf phantomjs-2.1.1-linux-x86_64.tar.bz2
            mv phantomjs-2.1.1-linux-x86_64 /usr/local/share
            ln -sf /usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin
            rm phantomjs-2.1.1-linux-x86_64.tar.bz2
      - checkout
      - run:
          name: Install app dependencies
          command: |
            bundle install
            npm i
      - run:
          name: Generate test app
          command: bundle exec rake decidim:generate_test_app
      - run:
          name: Run tests
          command: |
            bundle exec rake
      - store_artifacts:
          path: /code/spec/decidim_dummy_app/tmp/capybara
